# Generated by Django 4.2.11 on 2025-10-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
