# Generated by Django 4.2.11 on 2025-10-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ghl_notified',
            field=models.BooleanField(default=False),
        ),
    ]
