# Generated by Django 4.2.11 on 2025-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('ghl_access_token', models.CharField(blank=True, default='', max_length=255)),
                ('ghl_refresh_token', models.CharField(blank=True, default='', max_length=255)),
                ('ghl_location_id', models.CharField(blank=True, default='', max_length=100)),
                ('mp_access_token', models.CharField(blank=True, default='', max_length=255)),
                ('mp_refresh_token', models.CharField(blank=True, default='', max_length=255)),
                ('mp_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
